import { Inter } from "next/font/google";
import "./globals.css";
import ProvidersTheme from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Layout dark and light mode with Next.js and Tailwind CSS",
  description: "Generated by placidovenegas.dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <ProvidersTheme attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ProvidersTheme>
      </body>
    </html>
  );
}
